INSERT INTO USUARIO(nombre, clave, correo, activo) values('Alfonso de Leon','12345','adeleon@gmail.com','S')
GO
INSERT INTO ROL(Descripcion) VALUES('SUPER USUARIO')
GO
INSERT INTO ASIG_ROL(usuario_id, rol_id) VALUES(1,1)
GO
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Gestión de usuarios','#','',0)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Creación de usuario','#','',1)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Creación de Rol','#','',1)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Asignación de Rol','#','',1)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Asignación de accesos','#','',1)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Cambio de contraseña','#','',1)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Módulo de ventas','#','',0)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Cotización','#','',7)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Orden de Venta','#','',7)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Entre o envió','#','',7)
INSERT INTO MENU(Descripcion,Ruta,Icono,Raiz) VALUES ('Factura','#','',7)
GO
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(1,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(2,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(3,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(4,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(5,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(6,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(7,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(8,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(9,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(10,1)
INSERT INTO ASIG_ACCESO(menu_id,rol_id) VALUES(11,1)
